
     active environment : codraw_pl_2
    active env location : /home/users/blasota/anaconda3/envs/codraw_pl_2
            shell level : 2
       user config file : /home/users/blasota/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.20.5
         python version : 3.8.16.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/users/blasota/anaconda3  (writable)
      conda av data dir : /home/users/blasota/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/users/blasota/anaconda3/pkgs
                          /home/users/blasota/.conda/pkgs
       envs directories : /home/users/blasota/anaconda3/envs
                          /home/users/blasota/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.29.0 CPython/3.8.16 Linux/5.4.0-99-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1147:501
             netrc file : None
           offline mode : False

